### ISSUE TITLE
Support for `og` image generation on the website

### ISSUE THREAD

**Issue by yeganathan18** [gitwonk/gitwonk#2]
# Feature request

Right now, our website doesn't have any `og` image for pages and something that looks cool should work 🎨

For more context, check this out: https://vercel.com/docs/concepts/functions/edge-functions/og-image-generation

**Comment by dephraiim** [comment]
@yeganathan18 I would like to take this.

**Comment by yeganathan18** [comment]
@dephraiim sure 👍

**Comment by dephraiim** [comment]
@yeganathan18 is there an already existing design I can use or I should come up with one?

**Comment by yeganathan18** [comment]
@dephraiim  could you come up with a design? Let's see if it works. Meanwhile let me ping the team as well
